env:
  global:
    - CC_TEST_REPORTER_ID=3798532b8ba006dda3541198ac9e2b9b21825dc476540ee1d9397b0665f8d033
language: php
php:
  - 7.0
  - 7.1
  - 7.2
sudo: false

git:
 depth: 10000

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - git config --global user.email "travisci@example.com"
  - git config --global user.name "Travis CI Test"
before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version
install:
  - composer --verbose install
script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
