language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

git:
 depth: 10000

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

before_script:
  - git config --global user.email "travisci@example.com"
  - git config --global user.name "Travis CI Test"

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

addons:
  code_climate:
    repo_token: 3798532b8ba006dda3541198ac9e2b9b21825dc476540ee1d9397b0665f8d033

after_success:
  - vendor/bin/test-reporter
